### ISSUE TITLE
UI Improvements and Functional Fixes

### ISSUE THREAD

**Issue by sumitt-kun** [BitWebApp/BitWebApp-24#74]
Disclaimer: All tasks of an issue must be completed before submitting a pull request. Performance will be rated based on this criteria. More similar tasks can be added to this issue as per need.
1. Fetch and display awards in a table using React and Tailwind CSS.
2. Fetch and display projects in a table using React and Tailwind CSS.
3. Ensure loaders are visible in all forms using React and Tailwind CSS.
4. Fix confirmation dialogs (swals) to show entered data using SweetAlert2.
5. Add spinners to the admin login page using React and Tailwind CSS.
6. Test and rectify mobile responsiveness of all pages.
7. Add swals to show errors if a user tries to add repetitive data using SweetAlert2.
8. Fetch all student details in a table called "Student Details" and implement a percentage profile completion functionality using React and Tailwind CSS.

**Comment by Ankit8125** [comment]
Working on Swals issue and

**Comment by Hritabhash1** [comment]
i will see it
